app:
  name: api-legacy
  template:
    oidc_client_id: "ONECX_OIDC_CLIENT_CLIENT_ID"
  image:
    repository: "onecx/onecx-workspace-api-legacy"
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-ws:read ]
    microservice:
      spec:
        description: OneCX Workspace API Legacy
        name: OneCX Workspace API Legacy
